---
version: '3'

services:
     web:
       image: nginx:1.20-alpine
       container_name: nginx
       restart: always
       volumes:
           - ./website/:/usr/share/nginx/html/
           - ./nginx.conf:/etc/nginx/conf.d/default.conf
       networks:
           - nginx
       ports:
           - "8080:80"


     php:
       image: php:7.4.0-fpm-alpine
       container_name: php-fpm
       restart: always
       volumes:
           - ./website/:/usr/share/nginx/html/
       networks:
           - nginx

networks:
     nginx:
